import { readFile } from 'node:fs/promises';
const tables=['storeAudit','productProfiles','storeSettings','storeQuotes','supportCases','supportMessages','supportFiles','serviceZones','serviceBookings','inventoryChannels','inventoryEvents','inventoryOutbox','rewardLedger','rewardBenefits','rewardRedemptions','paymentRefunds','adminPasskeys','passkeyChallenges'];
export async function migrateCommerce(connection) {
 const sql=await readFile(new URL('../../db/migrations/20261009_commerce.sql',import.meta.url),'utf8');
 for(const statement of sql.split(';').filter(s=>s.trim()))await connection.query(statement);
 const [rows]=await connection.query('SELECT TABLE_NAME AS name,ENGINE AS engine FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN (?)',[tables]);
 const columns={storeAudit:'id,actorId,action,resourceId,details,createdAt',productProfiles:'productId,body,updatedAt',storeSettings:'name,body',storeQuotes:'id,userId,tokenHash,snapshot,expiresAt,status,orderId',supportCases:'id,userId,orderId,kind,subject,status',supportMessages:'id,caseId,actorId,message,attachments',supportFiles:'id,userId,caseId,extension',serviceZones:'id,postalCode,label,deliveryCents,installationCents,daysAhead,dailyCapacity,active',serviceBookings:'id,userId,orderId,zoneId,serviceDate,installation,status,snapshot',inventoryChannels:'id,label,secretHash,userId,enabled',inventoryEvents:'channelId,eventId,inputHash,orderId',inventoryOutbox:'id,productId,stock',rewardLedger:'id,userId,eventKey,points,reason',rewardBenefits:'id,name,description,points,active',rewardRedemptions:'id,userId,benefitId,snapshot,status',paymentRefunds:'id,orderId,actorId,provider,paymentId,providerRefundId,amountCents,state,reason',adminPasskeys:'id,userId,publicKey,counter,transports,label',passkeyChallenges:'id,userId,purpose,challenge,expiresAt'};
 for(const [table,list] of Object.entries(columns))await connection.query(`SELECT ${list} FROM ${table} LIMIT 0`);
 for(const [table,unique] of [['storeQuotes',['tokenHash']],['serviceZones',['postalCode']],['serviceBookings',['orderId']],['rewardLedger',['eventKey']],['paymentRefunds',['orderId']]]){const [indexes]=await connection.query(`SHOW INDEX FROM ${table}`);if(!indexes.some(row=>row.Non_unique===0&&unique.includes(row.Column_name)&&row.Seq_in_index===1))throw Error('Missing commerce unique constraint');}
 if(rows.length!==tables.length||rows.some(r=>r.engine!=='InnoDB'))throw Error('Commerce migration gate failed');
}
