// @ts-nocheck
import { cancelStripeCheckout } from './cancellations.mjs';
import { readFile } from 'node:fs/promises';
import { requestRefund,reconcileRefund } from './refunds.mjs';
import { paymentConfig } from '../payments/config';
import { z } from 'zod';
import { randomUUID,randomBytes } from 'node:crypto';
import { createRouter,publicQuery,authedQuery,adminQuery } from '../middleware';
import { getOrderPool } from '../queries/connection';
import { audit,transaction,json,ownedOrder,createQuote,publicQuote,redeem,serviceAvailability,digest } from './core.mjs';
const pool=()=>getOrderPool();
const id=z.number().int().positive();
const image=z.string().max(1000).refine(v=>/^\/(uploads|media)\/[a-zA-Z0-9/_.-]+$/.test(v),'Usa una imagen cargada en la tienda');
const profile=z.object({gallery:z.array(image).max(12),condition:z.string().max(1000),accessories:z.array(z.string().max(100)).max(20),unitCode:z.string().max(100),warranty:z.string().max(1000),dimensions:z.object({widthMm:z.number().min(100).max(4000),heightMm:z.number().min(100).max(3000),depthMm:z.number().min(1).max(1000),source:z.url().refine(v=>new URL(v).protocol==='https:')}).optional()});
const caseInput=z.object({orderId:id,kind:z.enum(['warranty','return','support']),subject:z.string().trim().min(3).max(160),message:z.string().trim().min(3).max(5000)});
export const commerceRouter=createRouter({
  cancelCheckout:authedQuery.input(z.object({orderId:id})).mutation(({ctx,input})=>cancelStripeCheckout(pool(),ctx.user,input.orderId,paymentConfig('stripe'))),
  inspectedReturn:adminQuery.input(z.object({orderId:id})).mutation(({ctx,input})=>transaction(pool(),async c=>{const order=await ownedOrder(c,ctx.user,input.orderId,true);const [refunds]=await c.execute("SELECT id FROM paymentRefunds WHERE orderId=? AND state='confirmed'",[input.orderId]);if(order.status!=='cancelled'||!refunds.length)throw new Error('Se requiere reembolso confirmado');if(order.inventoryReserved===1){const [items]=await c.execute('SELECT productId,quantity FROM orderItems WHERE orderId=? ORDER BY productId',[input.orderId]);for(const item of items)await c.execute('UPDATE products SET stock=stock+? WHERE id=?',[item.quantity,item.productId]);await c.execute('UPDATE orders SET inventoryReserved=0 WHERE id=?',[input.orderId]);await audit(c,ctx.user.id,'inventory.return.inspected',input.orderId);}return {success:true};})),
  advisorQuotes:authedQuery.query(async({ctx})=>{if(!['admin','agent'].includes(ctx.user.role))throw new Error('Acceso de asesor requerido');const [rows]=await pool().execute('SELECT id,userId,snapshot,status,expiresAt FROM storeQuotes ORDER BY createdAt DESC LIMIT 100');return rows.map(q=>({...q,snapshot:json(q.snapshot)}));}),
  advisorClose:authedQuery.input(z.object({id:z.string().uuid()})).mutation(({ctx,input})=>transaction(pool(),async c=>{if(!['admin','agent'].includes(ctx.user.role))throw new Error('Acceso de asesor requerido');await c.execute("UPDATE storeQuotes SET status='closed' WHERE id=? AND status='open'",[input.id]);await audit(c,ctx.user.id,'quote.advisor.close',input.id);return {success:true};})),
  monitor:adminQuery.query(async()=>{const result={health:null,backup:null,alert:null};for(const [key,file] of [['health','health.json'],['backup','backup-status.json'],['alert','important-alert.json']])try{const value=JSON.parse(await readFile(`/opt/samsung-backups/operations/${file}`,'utf8'));result[key]=key==='backup'?{at:value.at,verified:value.verified,sha256:value.sha256,tables:value.tables,files:Object.keys(value.files||{})}:value;}catch{}return result;}),
  refunds:adminQuery.query(async()=>{const [rows]=await pool().execute('SELECT id,orderId,provider,amountCents,state,reason,createdAt FROM paymentRefunds ORDER BY createdAt DESC LIMIT 100');return rows;}),
  refund:adminQuery.input(z.object({orderId:id,reason:z.string().trim().min(5).max(500)})).mutation(async({ctx,input})=>{const [rows]=await pool().execute('SELECT provider FROM paymentAttempts WHERE orderId=?',[input.orderId]);return requestRefund(pool(),ctx.user.id,input.orderId,input.reason,paymentConfig(rows[0]?.provider));}),
  refundReconcile:adminQuery.input(z.object({id:z.string().uuid()})).mutation(async({input})=>{const [rows]=await pool().execute('SELECT provider FROM paymentRefunds WHERE id=?',[input.id]);const config=paymentConfig(rows[0]?.provider);if(!config)throw new Error('Proveedor sin configuración');return reconcileRefund(pool(),input.id,config);}),
  profiles:publicQuery.query(async()=>{const [rows]=await pool().execute('SELECT productId,body FROM productProfiles');return rows.map(r=>({productId:Number(r.productId),...json(r.body)}));}),
  saveProfile:adminQuery.input(z.object({productId:id,profile})).mutation(({ctx,input})=>transaction(pool(),async c=>{const [rows]=await c.execute('SELECT id FROM products WHERE id=?',[input.productId]);if(!rows.length)throw new Error('Producto no encontrado');await c.execute('INSERT INTO productProfiles (productId,body) VALUES (?,?) ON DUPLICATE KEY UPDATE body=VALUES(body)',[input.productId,JSON.stringify(input.profile)]);await audit(c,ctx.user.id,'product.profile',input.productId);return {success:true};})),
  operations:adminQuery.query(async()=>{
    const queries=["SELECT COUNT(*) AS products,COALESCE(SUM(stock),0) AS units FROM products","SELECT id,name,model,stock FROM products WHERE stock<=2 ORDER BY stock,id LIMIT 100","SELECT status,COUNT(*) AS orders,COALESCE(SUM(total),0) AS total FROM orders GROUP BY status","SELECT id,actorId,action,resourceId,createdAt FROM storeAudit ORDER BY id DESC LIMIT 100","SELECT s.*,u.email FROM supportCases s JOIN users u ON u.id=s.userId ORDER BY s.id DESC LIMIT 100","SELECT * FROM serviceZones ORDER BY postalCode","SELECT * FROM serviceBookings ORDER BY serviceDate DESC LIMIT 100","SELECT id,label,enabled FROM inventoryChannels","SELECT * FROM rewardBenefits","SELECT r.id,r.userId,r.snapshot,r.status,r.createdAt FROM rewardRedemptions r ORDER BY createdAt DESC LIMIT 100","SELECT name,body FROM storeSettings","SELECT id,userId,snapshot,expiresAt,status FROM storeQuotes ORDER BY createdAt DESC LIMIT 100"];
    const data=await Promise.all(queries.map(async q=>(await pool().execute(q))[0]));return Object.fromEntries(['inventory','lowStock','orders','audit','cases','zones','bookings','channels','benefits','redemptions','settings','quotes'].map((key,i)=>[key,data[i]]));
  }),
  quoteCreate:authedQuery.input(z.object({items:z.array(z.object({productId:id,quantity:z.number().int().min(1).max(999)})).min(1).max(50)})).mutation(({ctx,input})=>createQuote(pool(),ctx.user.id,input.items)),
  quote:publicQuery.input(z.object({token:z.string().regex(/^[a-f0-9]{64}$/)})).query(({input})=>publicQuote(pool(),input.token)),
  quoteClose:adminQuery.input(z.object({id:z.string().uuid()})).mutation(({ctx,input})=>transaction(pool(),async c=>{await c.execute("UPDATE storeQuotes SET status='closed' WHERE id=? AND status='open'",[input.id]);await audit(c,ctx.user.id,'quote.close',input.id);return {success:true};})),
  portal:authedQuery.query(async({ctx})=>{const [cases]=await pool().execute('SELECT * FROM supportCases WHERE userId=? ORDER BY id DESC',[ctx.user.id]);const [ledger]=await pool().execute('SELECT points,reason,createdAt FROM rewardLedger WHERE userId=? ORDER BY id DESC LIMIT 100',[ctx.user.id]);const [balance]=await pool().execute('SELECT COALESCE(SUM(points),0) AS points FROM rewardLedger WHERE userId=?',[ctx.user.id]);const [benefits]=await pool().execute('SELECT * FROM rewardBenefits WHERE active=1');const [vouchers]=await pool().execute('SELECT id,snapshot,status FROM rewardRedemptions WHERE userId=? ORDER BY createdAt DESC',[ctx.user.id]);const [bookings]=await pool().execute('SELECT * FROM serviceBookings WHERE userId=? ORDER BY serviceDate DESC',[ctx.user.id]);return {cases,ledger,points:Number(balance[0].points),benefits,vouchers,bookings};}),
  caseCreate:authedQuery.input(caseInput).mutation(({ctx,input})=>transaction(pool(),async c=>{await ownedOrder(c,ctx.user,input.orderId);const [r]=await c.execute('INSERT INTO supportCases (userId,orderId,kind,subject) VALUES (?,?,?,?)',[ctx.user.id,input.orderId,input.kind,input.subject]);await c.execute('INSERT INTO supportMessages (caseId,actorId,message,attachments) VALUES (?,?,?,?)',[r.insertId,ctx.user.id,input.message,'[]']);return {id:Number(r.insertId)};})),
  messages:authedQuery.input(z.object({id})).query(async({ctx,input})=>{const [cases]=await pool().execute('SELECT userId FROM supportCases WHERE id=?',[input.id]);if(!cases.length || (ctx.user.role!=='admin'&&Number(cases[0].userId)!==ctx.user.id)) throw new Error('Caso no disponible');const [rows]=await pool().execute('SELECT * FROM supportMessages WHERE caseId=? ORDER BY id',[input.id]);return rows.map(r=>({...r,attachments:json(r.attachments)||[]}));}),
  reply:authedQuery.input(z.object({id,message:z.string().trim().min(1).max(5000),attachments:z.array(z.string().uuid()).max(5)})).mutation(({ctx,input})=>transaction(pool(),async c=>{const [cases]=await c.execute('SELECT userId,status FROM supportCases WHERE id=? FOR UPDATE',[input.id]);if(!cases.length || (ctx.user.role!=='admin'&&Number(cases[0].userId)!==ctx.user.id))throw new Error('Caso no disponible');for(const file of input.attachments){const [r]=await c.execute('SELECT id FROM supportFiles WHERE id=? AND userId=? AND (caseId IS NULL OR caseId=?) FOR UPDATE',[file,ctx.user.id,input.id]);if(!r.length)throw new Error('Archivo no disponible');await c.execute('UPDATE supportFiles SET caseId=? WHERE id=?',[input.id,file]);}await c.execute('INSERT INTO supportMessages (caseId,actorId,message,attachments) VALUES (?,?,?,?)',[input.id,ctx.user.id,input.message,JSON.stringify(input.attachments)]);if(ctx.user.role==='admin')await audit(c,ctx.user.id,'support.reply',input.id);return {success:true};})),
  caseStatus:adminQuery.input(z.object({id,status:z.enum(['open','review','resolved','closed'])})).mutation(({ctx,input})=>transaction(pool(),async c=>{await c.execute('UPDATE supportCases SET status=? WHERE id=?',[input.status,input.id]);await audit(c,ctx.user.id,'support.status',input.id,{status:input.status});return {success:true};})),
  service:publicQuery.input(z.object({postalCode:z.string().regex(/^\d{5}$/)})).query(({input})=>serviceAvailability(pool(),input.postalCode)),
  saveZone:adminQuery.input(z.object({postalCode:z.string().regex(/^\d{5}$/),label:z.string().min(2).max(120),deliveryCents:z.number().int().min(0).max(10000000),installationCents:z.number().int().min(0).max(10000000),daysAhead:z.number().int().min(1).max(30),dailyCapacity:z.number().int().min(1).max(1000),active:z.boolean()})).mutation(({ctx,input})=>transaction(pool(),async c=>{await c.execute('INSERT INTO serviceZones (postalCode,label,deliveryCents,installationCents,daysAhead,dailyCapacity,active) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE label=VALUES(label),deliveryCents=VALUES(deliveryCents),installationCents=VALUES(installationCents),daysAhead=VALUES(daysAhead),dailyCapacity=VALUES(dailyCapacity),active=VALUES(active)',[input.postalCode,input.label,input.deliveryCents,input.installationCents,input.daysAhead,input.dailyCapacity,input.active]);await audit(c,ctx.user.id,'delivery.zone',input.postalCode);return {success:true};})),
  bookingStatus:adminQuery.input(z.object({id:z.string().uuid(),status:z.enum(['requested','scheduled','completed'])})).mutation(({ctx,input})=>transaction(pool(),async c=>{const [rows]=await c.execute("SELECT b.id,b.status,p.state FROM serviceBookings b JOIN paymentAttempts p ON p.orderId=b.orderId WHERE b.id=? FOR UPDATE",[input.id]);if(rows[0]?.state!=='paid')throw new Error('Confirma el pago antes de programar');if(rows[0].status!==input.status&&!({requested:['scheduled'],scheduled:['completed'],completed:[]}[rows[0].status]||[]).includes(input.status))throw new Error('Transición de agenda inválida');await c.execute('UPDATE serviceBookings SET status=? WHERE id=?',[input.status,input.id]);await audit(c,ctx.user.id,'delivery.status',input.id,{status:input.status});return {success:true};})),
  rewardsConfig:adminQuery.input(z.object({enabled:z.boolean(),pointsPer100:z.number().int().min(1).max(1000)})).mutation(({ctx,input})=>transaction(pool(),async c=>{await c.execute("INSERT INTO storeSettings (name,body) VALUES ('rewards',?) ON DUPLICATE KEY UPDATE body=VALUES(body)",[JSON.stringify(input)]);await audit(c,ctx.user.id,'rewards.configure','rewards',input);return {success:true};})),
  saveBenefit:adminQuery.input(z.object({id:id.optional(),name:z.string().min(2).max(120),description:z.string().max(500),points:z.number().int().min(1).max(10000000),active:z.boolean()})).mutation(({ctx,input})=>transaction(pool(),async c=>{if(input.id)await c.execute('UPDATE rewardBenefits SET name=?,description=?,points=?,active=? WHERE id=?',[input.name,input.description,input.points,input.active,input.id]);else await c.execute('INSERT INTO rewardBenefits (name,description,points,active) VALUES (?,?,?,?)',[input.name,input.description,input.points,input.active]);await audit(c,ctx.user.id,'rewards.benefit',input.id);return {success:true};})),
  redeem:authedQuery.input(z.object({benefitId:id})).mutation(({ctx,input})=>redeem(pool(),ctx.user.id,input.benefitId)),
  fulfillReward:adminQuery.input(z.object({id:z.string().uuid()})).mutation(({ctx,input})=>transaction(pool(),async c=>{await c.execute("UPDATE rewardRedemptions SET status='fulfilled' WHERE id=? AND status='issued'",[input.id]);await audit(c,ctx.user.id,'rewards.fulfill',input.id);return {success:true};})),
  createChannel:adminQuery.input(z.object({label:z.string().trim().min(2).max(100)})).mutation(({ctx,input})=>transaction(pool(),async c=>{const id=randomUUID(),secret=randomBytes(32).toString('hex');await c.execute('INSERT INTO inventoryChannels (id,label,secretHash,userId) VALUES (?,?,?,?)',[id,input.label,digest(secret),ctx.user.id]);await audit(c,ctx.user.id,'inventory.channel',id);return {id,secret};})),
  channelStatus:adminQuery.input(z.object({id:z.string().uuid(),enabled:z.boolean()})).mutation(({ctx,input})=>transaction(pool(),async c=>{await c.execute('UPDATE inventoryChannels SET enabled=? WHERE id=?',[input.enabled,input.id]);await audit(c,ctx.user.id,'inventory.channel.status',input.id,{enabled:input.enabled});return {success:true};})),
});
