import test from 'node:test';import assert from 'node:assert/strict';import {createPool} from 'mysql2/promise';import {randomUUID} from 'node:crypto';
import {migrateCommerce} from '../api/commerce/migrate.mjs';
import {transaction,createQuote,publicQuote,redeem,awardRewards,reserveService,ownedOrder} from '../api/commerce/core.mjs';
import {startCheckout} from '../api/payments/checkout-service.mjs';import {requestRefund} from '../api/commerce/refunds.mjs';
test('commerce transactions use a dedicated real MySQL schema',{skip:!process.env.MYSQL_TEST_URL},async t=>{
 assert.equal(new URL(process.env.MYSQL_TEST_URL).pathname,'/samsung_store_test');const pool=createPool(process.env.MYSQL_TEST_URL);
 try{
  await migrateCommerce(pool);await migrateCommerce(pool);
  // Earlier inventory suite creates the shared legacy fixture schema.
  for(const [name,type] of [['model','VARCHAR(100)'],['imageUrl','TEXT']]){const [r]=await pool.query(`SHOW COLUMNS FROM products LIKE '${name}'`);if(!r.length)await pool.query(`ALTER TABLE products ADD COLUMN ${name} ${type}`);}
  await pool.query('CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255),email VARCHAR(320),role VARCHAR(30),password VARCHAR(255)) ENGINE=InnoDB');
  await pool.execute("INSERT INTO users (id,name,email,role) VALUES (50001,'Commerce fixture','commerce@example.invalid','client') ON DUPLICATE KEY UPDATE name=VALUES(name)");
  await pool.query('DELETE FROM productProfiles');await pool.query('DELETE FROM storeQuotes');await pool.query('DELETE FROM rewardRedemptions');await pool.query('DELETE FROM rewardLedger');await pool.query('DELETE FROM rewardBenefits');await pool.query('DELETE FROM serviceBookings');await pool.query('DELETE FROM serviceZones');await pool.query('DELETE FROM paymentRefunds');await pool.query('DELETE FROM storeSettings');
  await pool.execute("INSERT INTO products (id,name,model,price,stock,imageUrl) VALUES (50001,'Fixture TV','UN75DU8000',1000,10,'/media/fixture.webp') ON DUPLICATE KEY UPDATE price=1000,stock=10");
  const items=[{productId:50001,quantity:1}],shippingAddress={name:'Fixture',email:'commerce@example.invalid',phone:'5555555555',address:'Fixture 123',city:'CDMX',postalCode:'01000'};
  await t.test('quote fixes server price, hides owner and refuses other account conversion',async()=>{const q=await createQuote(pool,50001,items);assert.equal((await publicQuote(pool,q.token)).snapshot.total,'1000.00');assert.equal('userId' in await publicQuote(pool,q.token),false);await pool.execute('UPDATE products SET price=1200 WHERE id=50001');await assert.rejects(startCheckout(pool,50002,{provider:'stripe',requestKey:randomUUID(),items,shippingAddress,quoteToken:q.token},{},{stripe:async()=>({sessionId:'cs_q',url:'https://checkout.stripe.com/c/pay/q'})}));const order=await startCheckout(pool,50001,{provider:'stripe',requestKey:randomUUID(),items,shippingAddress,quoteToken:q.token},{},{stripe:async snapshot=>{assert.equal(snapshot.total,'1000.00');return {sessionId:'cs_q',url:'https://checkout.stripe.com/c/pay/q'};}});assert.ok(order.orderId);await assert.rejects(startCheckout(pool,50001,{provider:'stripe',requestKey:randomUUID(),items,shippingAddress,quoteToken:q.token},{},{}));});
  await t.test('delivery capacity serializes concurrent reservations and forbids other postal code',async()=>{const [z]=await pool.execute("INSERT INTO serviceZones (postalCode,label,deliveryCents,installationCents,daysAhead,dailyCapacity) VALUES ('01000','Fixture zone',10000,5000,1,1)");const date=new Date(Date.now()+86400000).toISOString().slice(0,10),selection={zoneId:Number(z.insertId),date,installation:true};await assert.rejects(transaction(pool,c=>reserveService(c,50001,80000,selection,'99999')));const results=await Promise.allSettled([80001,80002].map(orderId=>transaction(pool,c=>reserveService(c,50001,orderId,selection,'01000'))));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='fulfilled').value.price,'150.00');});
  await t.test('two simultaneous redemptions cannot spend the same points',async()=>{await pool.execute("INSERT INTO rewardLedger (userId,eventKey,points,reason) VALUES (50001,'fixture-credit',100,'Fixture')");const [b]=await pool.execute("INSERT INTO rewardBenefits (name,description,points) VALUES ('Fixture','Fixture',100)");const results=await Promise.allSettled([redeem(pool,50001,Number(b.insertId)),redeem(pool,50001,Number(b.insertId))]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);});
  await t.test('rewards need authoritative paid + delivered order and award only once',async()=>{await pool.execute("INSERT INTO storeSettings (name,body) VALUES ('rewards',?)",[JSON.stringify({enabled:true,pointsPer100:1})]);const [o]=await pool.execute("INSERT INTO orders (userId,total,status,inventoryReserved) VALUES (50001,1000,'delivered',0)");await transaction(pool,c=>awardRewards(c,Number(o.insertId)));let [ledger]=await pool.execute('SELECT * FROM rewardLedger WHERE eventKey=?',[`order:${o.insertId}`]);assert.equal(ledger.length,0);await pool.execute("INSERT INTO paymentAttempts (id,userId,requestKey,inputHash,provider,orderId,state,settlementId) VALUES (?,50001,?,'fixture','stripe',?,'paid','pi_fixture_reward')",[randomUUID(),randomUUID(),o.insertId]);await transaction(pool,c=>awardRewards(c,Number(o.insertId)));await transaction(pool,c=>awardRewards(c,Number(o.insertId)));[ledger]=await pool.execute('SELECT * FROM rewardLedger WHERE eventKey=?',[`order:${o.insertId}`]);assert.equal(ledger.length,1);assert.equal(ledger[0].points,10);await assert.rejects(ownedOrder(pool,{id:50002,role:'client'},Number(o.insertId)));});
  await t.test('ambiguous refund is durable and never sends another POST',async()=>{const [o]=await pool.execute("INSERT INTO orders (userId,total,status,inventoryReserved) VALUES (50001,1000,'processing',1)");await pool.execute("INSERT INTO paymentAttempts (id,userId,requestKey,inputHash,provider,orderId,state,settlementId) VALUES (?,50001,?,'fixture','stripe',?,'paid','pi_ambiguous')",[randomUUID(),randomUUID(),o.insertId]);let calls=0;const remote=async()=>{calls++;throw Error('timeout');};await assert.rejects(requestRefund(pool,50001,Number(o.insertId),'Fixture reason',{secretKey:'fixture'},remote));const r=await requestRefund(pool,50001,Number(o.insertId),'Fixture reason',{secretKey:'fixture'},remote);assert.equal(r.state,'review');assert.equal(calls,1);});
 }finally{await pool.end();}
});
