import test from 'node:test';import assert from 'node:assert/strict';
import { searchCatalog } from '../src/lib/catalog-search.mjs';
import { calibratedScreenWidth,screenDimensions } from '../src/lib/room-scale.mjs';
import { rewardPoints,serviceDates } from '../api/commerce/core.mjs';
import { providerRefund } from '../api/commerce/refunds.mjs';
test('catalogue search composes actual size, budget, stock and technology without fabricated matches',()=>{const products=[{model:'UN75DU8000',name:'Crystal UHD',price:13400,stock:1},{model:'QN77S90D',name:'OLED',price:29000,stock:1},{model:'UN75DU8000',name:'Crystal UHD',price:12000,stock:0}];assert.deepEqual(searchCatalog(products,'quiero 75 pulgadas hasta 20 mil disponibles'),[products[0]]);assert.deepEqual(searchCatalog(products,'OLED hasta 20 mil'),[]);assert.deepEqual(searchCatalog(products,'UN75DU8000'),[products[0],products[2]]);});
test('room calibration uses physical 16:9 dimensions and rejects invalid references',()=>{assert.ok(Math.abs(screenDimensions(75).widthCm-166.04)<.1);assert.ok(Math.abs(calibratedScreenWidth(1000,.8,300,75)-442.76)<1);assert.throws(()=>calibratedScreenWidth(1000,0,300,75));assert.throws(()=>screenDimensions(0));});
test('reward rules round complete hundred pesos down and service dates honor lead time',()=>{assert.equal(rewardPoints('199.99',2),2);assert.equal(rewardPoints('200.00',2),4);assert.throws(()=>rewardPoints('100',1.5));assert.equal(serviceDates({daysAhead:2},new Date('2026-10-09T23:00:00Z'))[0],'2026-10-11');});
test('refunds use fixed provider endpoints, canonical amounts and stable idempotency',async()=>{const r={id:'refund-id',provider:'stripe',paymentId:'pi_fixture',amountCents:1340000};const calls=[];const fetcher=async(url,options)=>{calls.push([url,options]);return {ok:true,json:async()=>({id:'re_fixture',status:'succeeded',payment_intent:'pi_fixture',amount:1340000,currency:'mxn'})};};assert.equal((await providerRefund(r,{secretKey:'fixture'},fetcher)).state,'confirmed');assert.equal(calls[0][0],'https://api.stripe.com/v1/refunds');assert.equal(calls[0][1].headers['Idempotency-Key'],'refund-refund-id');assert.equal(calls[0][1].body.get('amount'),'1340000');await assert.rejects(providerRefund({...r,paymentId:'../unsafe'},{},fetcher));await assert.rejects(providerRefund(r,{},async()=>({ok:true,json:async()=>({id:'re',payment_intent:'pi_fixture',currency:'usd',amount:1340000})})));});
