import {spawn} from 'node:child_process';import {once} from 'node:events';import {createServer} from 'node:net';import {setTimeout as delay} from 'node:timers/promises';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {chromium} from 'playwright';import {hashPassword} from '../api/lib/password-core.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import {createPool} from 'mysql2/promise';import {randomUUID} from 'node:crypto';
import {migrateCommerce} from '../api/commerce/migrate.mjs';
import {transaction,createQuote,publicQuote,redeem,awardRewards,reserveService,ownedOrder,serviceDates} from '../api/commerce/core.mjs';
import {cancelStripeCheckout} from '../api/commerce/cancellations.mjs';
import {startCheckout} from '../api/payments/checkout-service.mjs';import {requestRefund} from '../api/commerce/refunds.mjs';
test('commerce transactions use a dedicated real MySQL schema',{skip:!process.env.MYSQL_TEST_URL},async t=>{
 assert.equal(new URL(process.env.MYSQL_TEST_URL).pathname,'/samsung_store_test');const pool=createPool(process.env.MYSQL_TEST_URL);
 try{
  await migrateCommerce(pool);await migrateCommerce(pool);
  // Earlier inventory suite creates the shared legacy fixture schema.
  for(const [name,type] of [['model','VARCHAR(100)'],['imageUrl','TEXT']]){const [r]=await pool.query(`SHOW COLUMNS FROM products LIKE '${name}'`);if(!r.length)await pool.query(`ALTER TABLE products ADD COLUMN ${name} ${type}`);}
  await pool.query('CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255),email VARCHAR(320),role VARCHAR(30),password VARCHAR(255)) ENGINE=InnoDB');
  await pool.execute("INSERT INTO users (id,name,email,role) VALUES (50001,'Commerce fixture','commerce@example.invalid','client') ON DUPLICATE KEY UPDATE name=VALUES(name)");
  await pool.query('DELETE FROM productProfiles');await pool.query('DELETE FROM storeQuotes');await pool.query('DELETE FROM rewardRedemptions');await pool.query('DELETE FROM rewardLedger');await pool.query('DELETE FROM rewardBenefits');await pool.query('DELETE FROM serviceBookings');await pool.query('DELETE FROM serviceZones');await pool.query('DELETE FROM paymentRefunds');await pool.query('DELETE FROM storeSettings');
  await pool.execute("INSERT INTO products (id,name,model,price,stock,imageUrl) VALUES (50001,'Fixture TV','UN75DU8000',1000,10,'/media/fixture.webp') ON DUPLICATE KEY UPDATE price=1000,stock=10");
  const items=[{productId:50001,quantity:1}],shippingAddress={name:'Fixture',email:'commerce@example.invalid',phone:'5555555555',address:'Fixture 123',city:'CDMX',postalCode:'01000'};
  await t.test('quote fixes server price, hides owner and refuses other account conversion',async()=>{const q=await createQuote(pool,50001,items);assert.equal((await publicQuote(pool,q.token)).snapshot.total,'1000.00');assert.equal('userId' in await publicQuote(pool,q.token),false);await pool.execute('UPDATE products SET price=1200 WHERE id=50001');await assert.rejects(startCheckout(pool,50002,{provider:'stripe',requestKey:randomUUID(),items,shippingAddress,quoteToken:q.token},{},{stripe:async()=>({sessionId:'cs_q',url:'https://checkout.stripe.com/c/pay/q'})}));const order=await startCheckout(pool,50001,{provider:'stripe',requestKey:randomUUID(),items,shippingAddress,quoteToken:q.token},{},{stripe:async snapshot=>{assert.equal(snapshot.total,'1000.00');return {sessionId:'cs_q',url:'https://checkout.stripe.com/c/pay/q'};}});assert.ok(order.orderId);await assert.rejects(startCheckout(pool,50001,{provider:'stripe',requestKey:randomUUID(),items,shippingAddress,quoteToken:q.token},{},{}));});
  await t.test('delivery capacity serializes concurrent reservations and forbids other postal code',async()=>{const [z]=await pool.execute("INSERT INTO serviceZones (postalCode,label,deliveryCents,installationCents,daysAhead,dailyCapacity) VALUES ('01000','Fixture zone',10000,5000,1,1)");const date=serviceDates({daysAhead:1})[0],selection={zoneId:Number(z.insertId),date,installation:true};await assert.rejects(transaction(pool,c=>reserveService(c,50001,80000,selection,'99999')));const results=await Promise.allSettled([80001,80002].map(orderId=>transaction(pool,c=>reserveService(c,50001,orderId,selection,'01000'))));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='fulfilled').value.price,'150.00');});
  await t.test('two simultaneous redemptions cannot spend the same points',async()=>{await pool.execute("INSERT INTO rewardLedger (userId,eventKey,points,reason) VALUES (50001,'fixture-credit',100,'Fixture')");const [b]=await pool.execute("INSERT INTO rewardBenefits (name,description,points) VALUES ('Fixture','Fixture',100)");const results=await Promise.allSettled([redeem(pool,50001,Number(b.insertId)),redeem(pool,50001,Number(b.insertId))]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);});
  await t.test('rewards need authoritative paid + delivered order and award only once',async()=>{await pool.execute("INSERT INTO storeSettings (name,body) VALUES ('rewards',?)",[JSON.stringify({enabled:true,pointsPer100:1})]);const [o]=await pool.execute("INSERT INTO orders (userId,total,status,inventoryReserved) VALUES (50001,1000,'delivered',0)");await transaction(pool,c=>awardRewards(c,Number(o.insertId)));let [ledger]=await pool.execute('SELECT * FROM rewardLedger WHERE eventKey=?',[`order:${o.insertId}`]);assert.equal(ledger.length,0);await pool.execute("INSERT INTO paymentAttempts (id,userId,requestKey,inputHash,provider,orderId,state,settlementId) VALUES (?,50001,?,'fixture','stripe',?,'paid','pi_fixture_reward')",[randomUUID(),randomUUID(),o.insertId]);await transaction(pool,c=>awardRewards(c,Number(o.insertId)));await transaction(pool,c=>awardRewards(c,Number(o.insertId)));[ledger]=await pool.execute('SELECT * FROM rewardLedger WHERE eventKey=?',[`order:${o.insertId}`]);assert.equal(ledger.length,1);assert.equal(ledger[0].points,10);await assert.rejects(ownedOrder(pool,{id:50002,role:'client'},Number(o.insertId)));});
  await t.test('ambiguous refund is durable and never sends another POST',async()=>{const [o]=await pool.execute("INSERT INTO orders (userId,total,status,inventoryReserved) VALUES (50001,1000,'processing',1)");await pool.execute("INSERT INTO paymentAttempts (id,userId,requestKey,inputHash,provider,orderId,state,settlementId) VALUES (?,50001,?,'fixture','stripe',?,'paid','pi_ambiguous')",[randomUUID(),randomUUID(),o.insertId]);let calls=0;const remote=async()=>{calls++;throw Error('timeout');};await assert.rejects(requestRefund(pool,50001,Number(o.insertId),'Fixture reason',{secretKey:'fixture'},remote));const r=await requestRefund(pool,50001,Number(o.insertId),'Fixture reason',{secretKey:'fixture'},remote);assert.equal(r.state,'review');assert.equal(calls,1);});
 await t.test('Stripe cancellation releases reserved inventory only after authoritative expiry and only once',async()=>{
    const request={provider:'stripe',requestKey:randomUUID(),items,shippingAddress};const attempt=await startCheckout(pool,50001,request,{},{stripe:async()=>({sessionId:'cs_cancel_fixture',url:'https://checkout.stripe.com/c/pay/cancel'})});
    const [before]=await pool.execute('SELECT stock FROM products WHERE id=50001');
    const unsafe=async()=>({ok:true,json:async()=>({id:'cs_cancel_fixture',client_reference_id:attempt.reference,status:'complete',payment_status:'paid',payment_intent:'pi_paid'})});
    await assert.rejects(cancelStripeCheckout(pool,{id:50001,role:'client'},attempt.orderId,{secretKey:'fixture'},unsafe));
    const safe=async()=>({ok:true,json:async()=>({id:'cs_cancel_fixture',client_reference_id:attempt.reference,status:'expired',payment_status:'unpaid',payment_intent:null})});
    await cancelStripeCheckout(pool,{id:50001,role:'client'},attempt.orderId,{secretKey:'fixture'},safe);await cancelStripeCheckout(pool,{id:50001,role:'client'},attempt.orderId,{secretKey:'fixture'},safe);
    const [after]=await pool.execute('SELECT stock FROM products WHERE id=50001');assert.equal(after[0].stock,before[0].stock+1);
  });
  await t.test('confirmed full refund reverses rewards once and does not restock shipped goods without inspection',async()=>{
    const attempt=await startCheckout(pool,50001,{provider:'stripe',requestKey:randomUUID(),items,shippingAddress},{},{stripe:async()=>({sessionId:'cs_refund_fixture',url:'https://checkout.stripe.com/c/pay/refund'})});
    await pool.execute("UPDATE paymentAttempts SET state='paid',settlementId='pi_refund_fixture' WHERE id=?",[attempt.reference]);await pool.execute("UPDATE orders SET status='delivered' WHERE id=?",[attempt.orderId]);await transaction(pool,c=>awardRewards(c,attempt.orderId));
    const [before]=await pool.execute('SELECT stock FROM products WHERE id=50001');const [order]=await pool.execute('SELECT total FROM orders WHERE id=?',[attempt.orderId]);
    let calls=0;const remote=async()=>{calls++;return {ok:true,json:async()=>({id:'re_refund_fixture',payment_intent:'pi_refund_fixture',currency:'mxn',amount:Math.round(Number(order[0].total)*100),status:'succeeded'})};};
    await requestRefund(pool,50002,attempt.orderId,'Fixture confirmed refund',{secretKey:'fixture'},remote);await requestRefund(pool,50002,attempt.orderId,'Fixture duplicate refund',{secretKey:'fixture'},remote);assert.equal(calls,1);
    const [after]=await pool.execute('SELECT stock FROM products WHERE id=50001');assert.equal(after[0].stock,before[0].stock);const [debit]=await pool.execute('SELECT points FROM rewardLedger WHERE eventKey=?',[`refund:${attempt.orderId}`]);assert.equal(debit.length,1);assert.equal(debit[0].points,-12);
  });
 await t.test('compiled commerce API and mobile portal enforce ownership, private evidence, roles and origins',async()=>{
    const password='commerce-fixture-password';await pool.execute('UPDATE users SET password=? WHERE id=50001',[await hashPassword(password)]);
    for(const [uid,role] of [[50002,'admin'],[50003,'client']])await pool.execute('INSERT INTO users (id,name,email,password,role) VALUES (?,?,?,?,?) ON DUPLICATE KEY UPDATE password=VALUES(password),role=VALUES(role)',[uid,'Commerce fixture',`commerce-${uid}@example.invalid`,await hashPassword(password),role]);
    for(const [name,type] of [['createdAt','TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL'],['agentId','BIGINT UNSIGNED NULL']]){const [columns]=await pool.query(`SHOW COLUMNS FROM orders LIKE '${name}'`);if(!columns.length)await pool.query(`ALTER TABLE orders ADD COLUMN ${name} ${type}`);}
    const dir=await mkdtemp(path.join(tmpdir(),'commerce-private-'));const listener=createServer();listener.listen(0,'127.0.0.1');await once(listener,'listening');const port=listener.address().port;await new Promise(r=>listener.close(r));const origin=`http://localhost:${port}`;
    const server=spawn(process.execPath,['dist/boot.js'],{env:{...process.env,NODE_ENV:'production',BIND_HOST:'127.0.0.1',PORT:String(port),APP_ID:'commerce-test',APP_SECRET:'commerce-test-only',DATABASE_URL:process.env.MYSQL_TEST_URL,SITE_ORIGIN:origin,SUPPORT_PRIVATE_DIR:dir,PAYMENTS_ENABLED:'0'},stdio:['ignore','pipe','pipe']});let browser,output='';server.stderr.on('data',d=>output+=d);
    try{
      for(let i=0;i<80;i++){if(server.exitCode!==null)throw Error(output);try{if((await fetch(origin)).ok)break;}catch{}await delay(100);}
      const post=async(name,input,cookie,headers={})=>fetch(origin+'/api/trpc/'+name,{method:'POST',headers:{'content-type':'application/json',...(cookie?{cookie}:{}),...headers},body:JSON.stringify({json:input})});
      const login=async email=>{const r=await post('localAuth.login',{email,password,isAdmin:false});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];};
      const owner=await login('commerce@example.invalid'),admin=await login('commerce-50002@example.invalid'),other=await login('commerce-50003@example.invalid');
      assert.equal((await post('commerce.caseCreate',{orderId:1,kind:'support',subject:'Cross-site',message:'Forbidden'},owner,{Origin:'https://evil.example'})).status,403);
      const [orders]=await pool.query('SELECT id FROM orders WHERE userId=50001 LIMIT 1');
      const created=await post('commerce.caseCreate',{orderId:Number(orders[0].id),kind:'warranty',subject:'Fixture support',message:'Fixture message'},owner);assert.equal(created.status,200);const caseId=(await created.json()).result.data.json.id;
      const query=async(name,input,cookie)=>fetch(origin+'/api/trpc/'+name+'?input='+encodeURIComponent(JSON.stringify({json:input})),{headers:{cookie}});
      assert.notEqual((await query('commerce.messages',{id:caseId},other)).status,200);
      const form=new FormData();form.set('file',new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jYFkAAAAASUVORK5CYII=','base64')],{type:'image/png'}),'evidence.png');
      const upload=await fetch(origin+'/api/support/file',{method:'POST',headers:{cookie:owner},body:form});assert.equal(upload.status,200);const fileId=(await upload.json()).id;
      assert.equal((await fetch(origin+'/api/support/file/'+fileId,{headers:{cookie:other}})).status,404);
      assert.equal((await fetch(origin+'/uploads/'+fileId+'.webp')).status,404);
      assert.equal((await post('commerce.reply',{id:caseId,message:'Attached evidence',attachments:[fileId]},owner)).status,200);
      assert.equal((await fetch(origin+'/api/support/file/'+fileId,{headers:{cookie:admin}})).status,200);
      assert.notEqual((await query('commerce.operations',undefined,owner)).status,200);assert.equal((await query('commerce.operations',undefined,admin)).status,200);
      const response=await post('commerce.createChannel',{label:'Fixture POS'},admin);assert.equal(response.status,200);const channel=(await response.json()).result.data.json;
      const headers={'Authorization':`Bearer ${channel.secret}`,'content-type':'application/json'};const sale={eventId:'fixture-sale',items:[{productId:50001,quantity:1}]};
      const first=await fetch(origin+`/api/inventory/${channel.id}/sale`,{method:'POST',headers,body:JSON.stringify(sale)});assert.equal(first.status,200);const firstBody=await first.json();const second=await fetch(origin+`/api/inventory/${channel.id}/sale`,{method:'POST',headers,body:JSON.stringify(sale)});assert.equal((await second.json()).orderId,firstBody.orderId);
      assert.equal((await fetch(origin+`/api/inventory/${channel.id}`)).status,401);
      browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||chromium.executablePath()});const context=await browser.newContext({viewport:{width:390,height:844}});await context.addCookies([{name:owner.split('=')[0],value:owner.slice(owner.indexOf('=')+1),url:origin}]);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/mi-cuenta');await page.getByRole('heading',{name:'Estamos contigo'}).waitFor();await page.getByText(`Pedido #${orders[0].id}`,{exact:true}).waitFor();await page.getByRole('button',{name:/Fixture support/}).click();await page.getByText('Attached evidence',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
      await context.clearCookies();await context.addCookies([{name:admin.split('=')[0],value:admin.slice(admin.indexOf('=')+1),url:origin}]);await page.goto(origin+'/admin/operaciones');await page.getByRole('heading',{name:'Control maestro'}).waitFor();await page.getByRole('button',{name:'Seguridad',exact:true}).click();await page.getByRole('heading',{name:'Historial administrativo'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
    }finally{await browser?.close();if(server.exitCode===null){const end=once(server,'exit');server.kill('SIGTERM');await end;}await rm(dir,{recursive:true,force:true});}
  });
 }finally{await pool.end();}
});
