import assert from 'node:assert/strict';import {mkdtemp,writeFile,mkdir,readFile,rm} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {spawn} from 'node:child_process';import {createPool} from 'mysql2/promise';
if(!process.env.MYSQL_TEST_URL)throw new Error('Dedicated MySQL fixture required');assert.equal(new URL(process.env.MYSQL_TEST_URL).pathname,'/samsung_store_test');
const dir=await mkdtemp(path.join(tmpdir(),'monitor-test-'));const live=path.join(dir,'live'),bin=path.join(dir,'bin'),backups=path.join(dir,'backups');await mkdir(live);await mkdir(bin);await mkdir(path.join(live,'uploads'));await mkdir(path.join(dir,'samsung-private-support'));await writeFile(path.join(live,'uploads','fixture.txt'),'upload fixture');await writeFile(path.join(dir,'samsung-private-support','private.txt'),'private fixture');
const fixture={name:'samsung-store',pm2_env:{pm_cwd:live,status:'online',env:{DATABASE_URL:process.env.MYSQL_TEST_URL,UPLOAD_DIR:path.join(live,'uploads'),SUPPORT_PRIVATE_DIR:path.join(dir,'samsung-private-support')}}};await writeFile(path.join(bin,'pm2'),'#!/usr/bin/env node\nprocess.stdout.write('+JSON.stringify(JSON.stringify([fixture]))+')',{mode:0o700});
const pool=createPool(process.env.MYSQL_TEST_URL);
try{
 const child=spawn(process.execPath,['scripts/operations-monitor.mjs','backup'],{env:{...process.env,PATH:bin+path.delimiter+process.env.PATH,SAMSUNG_LIVE_DIR:live,SAMSUNG_MONITOR_DIR:backups},stdio:['ignore','pipe','pipe']});let output='';child.stdout.on('data',d=>output+=d);child.stderr.on('data',d=>output+=d);const code=await new Promise((r,j)=>{child.once('exit',r);child.once('error',j)});assert.equal(code,0,output);
 const status=JSON.parse(await readFile(path.join(backups,'backup-status.json'),'utf8'));assert.equal(status.verified,true);assert.match(status.sha256,/^[a-f0-9]{64}$/);for(const name of ['products','users','storeAudit','supportMessages','paymentAttempts'])assert.ok(name in status.tables);assert.deepEqual(Object.keys(status.files).sort(),['support','uploads']);const [tables]=await pool.query("SELECT SCHEMA_NAME FROM information_schema.SCHEMATA WHERE SCHEMA_NAME LIKE 'samsung_restore_%'");assert.equal(tables.length,0);console.log('Actual MySQL dump/restore verified: dedicated scratch database, original schema preserved, SHA-256, private media archives and cleanup');
}finally{await pool.end();await rm(dir,{recursive:true,force:true});}
