// @ts-nocheck
import samsungExamples from '../../docs/samsung-source-examples.json';
import { useState } from 'react';
import { Link } from 'react-router';
import { trpc } from '@/providers/trpc';
import { toast } from 'sonner';
import { uploadProductImage } from '@/lib/upload-image.mjs';
import { decodeRows,toApiRows,encodeCsv,exportRows,photoMatches } from '@/lib/catalog-batch.mjs';
import { ArrowLeft,Download,Upload,Plus,CheckCircle2,Search,ExternalLink,Trash2 } from 'lucide-react';

const button='rounded-xl px-4 py-2.5 text-sm font-semibold border border-slate-200 hover:bg-slate-50 disabled:opacity-40 disabled:cursor-not-allowed';
const primary=button+' bg-[#1428A0] text-white hover:bg-blue-800';
const input='w-full min-w-0 rounded-lg border border-slate-200 px-3 py-2 text-sm bg-white';
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function RateCard({row,kind,onSaved}) {
  const [rate,setRate]=useState(row.rate===null?'':String(row.rate));
  const [reason,setReason]=useState('');
  const mutation=trpc.adminTools.saveRate.useMutation({onSuccess:()=>{toast.success('Porcentaje guardado');setReason('');onSaved();},onError:e=>toast.error(e.message)});
  return <article className="rounded-2xl border border-slate-200 bg-white p-5 space-y-3">
    <div><h3 className="font-bold text-slate-900">{row.name} <span className="text-xs font-normal text-slate-500">#{row.userId}</span></h3><p className="text-sm text-slate-500">{kind==='network'?`Miembro vinculado: ${row.memberName} (#${row.memberId})`:`Agente · ${row.code}`}</p></div>
    <p className="text-xs rounded-lg bg-blue-50 text-blue-900 p-3">Beneficiario: <strong>{row.name}</strong>. {kind==='network'?'Esta tasa pertenece al referente de este vínculo, no al miembro de la fila.':'Tasa de venta propia configurada para este agente.'}</p>
    <div className="flex items-end gap-3"><label className="flex-1 text-sm font-semibold">Porcentaje (0–25%)<input aria-label={`Porcentaje ${kind} ${row.userId}${kind==='network'?` ${row.memberId}`:''}`} className={input+' mt-1'} type="number" min="0" max="25" step="0.01" value={rate} onChange={e=>setRate(e.target.value)}/></label><span className="pb-3 text-slate-500 text-sm">Actual: {row.rate===null?'sin definir':row.rate+'%'}</span></div>
    <label className="block text-sm font-semibold">Motivo del cambio<input className={input+' mt-1'} value={reason} maxLength={255} onChange={e=>setReason(e.target.value)} placeholder="Ej. Acuerdo comercial aprobado"/></label>
    <p className="text-xs text-slate-500">Ejemplo sobre $1,000: {rate!==''&&Number.isFinite(Number(rate))&&Number(rate)>=0&&Number(rate)<=25?`$${(Number(rate)*10).toFixed(2)} MXN`:'indica una tasa válida'}. No representa saldo ganado.</p>
    <button className={primary} disabled={mutation.isPending||rate===''||!Number.isFinite(Number(rate))||Number(rate)<0||Number(rate)>25||reason.trim().length<3} onClick={()=>mutation.mutate({kind,userId:Number(row.userId),...(kind==='network'?{memberId:Number(row.memberId)}:{}),rate:Number(rate),expectedVersion:row.version,reason})}>{mutation.isPending?'Guardando…':'Guardar porcentaje'}</button>
  </article>;
}

export default function AdminCatalog(){
  const [tab,setTab]=useState('catalog'),[query,setQuery]=useState(''),[rows,setRows]=useState([]),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[selected,setSelected]=useState([]),[editing,setEditing]=useState(null);
  const catalog=trpc.adminTools.catalog.useQuery();
  const rates=trpc.adminTools.rates.useQuery(undefined,{enabled:tab==='rates'});
  const previewMutation=trpc.adminTools.preview.useMutation({onSuccess:data=>setPreview({...data,requestId:crypto.randomUUID()}),onError:e=>toast.error(e.message)});
  const applyMutation=trpc.adminTools.applyBatch.useMutation({onSuccess:result=>{toast.success(`Lote guardado: ${result.created} creados y ${result.updated} actualizados`);setRows([]);setPreview(null);setSelected([]);setEditing(null);catalog.refetch();},onError:e=>toast.error(e.message)});
  const locked=busy||previewMutation.isPending||applyMutation.isPending;
  const changeRows=value=>{setRows(value);setPreview(null);};
  const edit=(index,key,value)=>changeRows(rows.map((r,i)=>i===index?{...r,[key]:value,...(['model','imageUrl','description','name','sourceUrl','sourceModel','imageSourceUrl'].includes(key)&&r.sourceStatus==='reviewed'?{sourceStatus:'pending'}:{})}:r));
  const products=catalog.data?.products||[];
  const visible=products.filter(p=>(p.name+' '+p.model+' '+p.id).toLowerCase().includes(query.toLowerCase()));
  const readFile=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>2_000_000)throw Error('Máximo 2 MB');changeRows(decodeRows(await file.text()));setEditing(null);}catch(err){toast.error(err.message);}};
  const photos=async e=>{const files=Array.from(e.target.files||[]);e.target.value='';const {matches,errors}=photoMatches(files,rows);if(errors.length){toast.error(errors.join('\n'));return;}setBusy(true);setPreview(null);const next=rows.map(r=>({...r}));try{for(const match of matches){next[match.index].imageUrl=await uploadProductImage(match.file);if(next[match.index].sourceStatus==='reviewed')next[match.index].sourceStatus='pending';}toast.success(`${matches.length} fotos cargadas. Revisa el lote antes de guardar.`);}catch(err){toast.error(err.message);}finally{setRows(next);setBusy(false);}};
  const pending=rows.length>0;
  return <div className="min-h-screen bg-[#f4f6fb] text-slate-800 pb-20">
    <header className="bg-[#0b1735] text-white px-5 py-7"><div className="max-w-6xl mx-auto"><Link className="text-blue-200 text-sm flex items-center gap-2" to="/admin"><ArrowLeft size={16}/>Panel administrativo</Link><h1 className="text-3xl font-bold mt-4">Catálogo y comisiones</h1><p className="text-blue-100/80 mt-2">Edita varios productos y define porcentajes con revisión antes de guardar.</p></div></header>
    <main className="max-w-6xl mx-auto px-4 pt-6 space-y-6">
      <nav className="flex gap-2" aria-label="Herramientas administrativas">{[['catalog','Catálogo por lotes'],['rates','Porcentajes y red']].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={tab===id?primary:button+' bg-white'}>{label}</button>)}</nav>
      {tab==='rates'?<>
        <div className="rounded-2xl bg-amber-50 border border-amber-200 p-5"><h2 className="font-bold">Configuración de porcentajes</h2><p className="text-sm mt-2">Los cambios se guardan con su motivo y responsable. La liquidación automática de comisiones continúa desactivada: guardar una tasa no genera pagos ni cambia saldos anteriores. Los ejemplos muestran un cálculo, no ingresos confirmados.</p></div>
        {rates.isError?<div role="alert" className="p-5 bg-red-50">No se pudieron cargar los porcentajes. {rates.error.message}<button className={button} onClick={()=>rates.refetch()}>Reintentar</button></div>:rates.isLoading?<p role="status">Cargando porcentajes…</p>:<>
          <h2 className="text-xl font-bold">Agentes · venta propia</h2><div className="grid gap-4 md:grid-cols-2">{rates.data?.agents.map(row=><RateCard key={'a'+row.userId+row.version} row={row} kind="agent" onSaved={()=>rates.refetch()}/>)}</div>{!rates.data?.agents.length&&<p>No hay agentes registrados. Agrégalos desde el panel administrativo.</p>}
          <h2 className="text-xl font-bold">Red de mercadeo · vínculos directos</h2><p className="text-sm">El nombre superior identifica a quien recibiría la comisión del vínculo. Los niveles generales 2 y 3 conservan su configuración previa.</p><div className="grid gap-4 md:grid-cols-2">{rates.data?.network.map(row=><RateCard key={'n'+row.userId+'-'+row.memberId+row.version} row={row} kind="network" onSaved={()=>rates.refetch()}/>)}</div>{!rates.data?.network.length&&<p>No hay vínculos directos registrados.</p>}
        </>}
      </>:<>
        {catalog.isError?<div role="alert" className="p-5 bg-red-50">No se pudo leer el catálogo: {catalog.error.message}<button className={button} onClick={()=>catalog.refetch()}>Reintentar</button></div>:<>
        <section className="bg-white rounded-2xl p-5 border border-slate-200 space-y-4">
          <div className="flex flex-wrap gap-2 items-center"><h2 className="text-xl font-bold mr-auto">1. Prepara tu lote</h2><button className={button} disabled={locked} onClick={()=>download('plantilla-catalogo.csv',encodeCsv([{model:'MODELO-EXACTO',name:'Nombre del producto',category:catalog.data?.categories[0]||'',price:'',stock:'0',featured:'no'}]))}><Download size={15} className="inline mr-2"/>Plantilla CSV</button><button className={button} disabled={!products.length||locked} onClick={()=>download('catalogo.csv',encodeCsv(exportRows(products,catalog.data?.evidence)))}>Exportar catálogo</button></div>
          <p className="text-sm text-slate-500">Carga CSV o JSON, hasta 100 filas. ID vacío crea un producto; un ID existente actualiza ese producto. Las celdas vacías conservan el valor actual. Usa punto decimal y precios propios en MXN.</p>
          <div className="flex flex-wrap gap-2"><label className={button+' cursor-pointer'}><Upload size={15} className="inline mr-2"/>Importar archivo<input aria-label="Importar archivo" type="file" accept=".csv,.json" className="sr-only" disabled={locked} onChange={readFile}/></label><button className={button} disabled={locked} onClick={()=>{changeRows(samsungExamples.map(p=>({model:p.model,name:p.title,category:p.model.startsWith('QN')?'oled':'crystal',price:'',stock:'0',imageUrl:p.image_url,description:`${p.size} · ${p.resolution} · ${p.refresh_rate}`,specs:JSON.stringify({Pantalla:p.size,Resolución:p.resolution,Frecuencia:p.refresh_rate}),sourceUrl:p.source_url,sourceModel:p.model,imageSourceUrl:p.source_url,sourceStatus:'pending',sourceNotes:'Referencia oficial consultada el 9 de octubre de 2026. Confirmar unidad y precio propios.'})));setEditing(null);}}>Ejemplos con fuente Samsung</button><button className={button} disabled={locked||rows.length>=100} onClick={()=>changeRows([...rows,{name:'',model:'',category:catalog.data?.categories[0]||'',price:'',stock:'0',imageUrl:'',featured:'no'}])}><Plus size={15} className="inline mr-2"/>Nuevo producto</button><button className={button} disabled={locked||!selected.length} onClick={()=>{changeRows(exportRows(products.filter(p=>selected.includes(p.id)),catalog.data?.evidence));setEditing(null);}}>Editar seleccionados ({selected.length})</button></div>
          <label className="flex gap-2 items-center"><Search size={18}/><input className={input} placeholder="Buscar por nombre, modelo o ID" value={query} onChange={e=>setQuery(e.target.value)}/></label>
          <div className="max-h-64 overflow-auto rounded-xl border"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Elegir</th><th className="text-left">Producto / modelo</th><th>Precio</th><th>Stock</th></tr></thead><tbody>{visible.map(p=><tr key={p.id} className="border-t"><td className="p-3 text-center"><input aria-label={`Seleccionar ${p.model} ${p.id}`} type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(e.target.checked?[...selected,p.id]:selected.filter(id=>id!==p.id))}/></td><td className="py-2">{p.name}<small className="block text-slate-500">#{p.id} · {p.model}</small></td><td className="p-2 text-right">${p.price}</td><td className="p-2 text-center">{p.stock}</td></tr>)}</tbody></table></div>
        </section>
        {pending&&<section className="bg-white rounded-2xl p-5 border border-slate-200 space-y-4">
          <div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold mr-auto">2. Edita y verifica · {rows.length} filas</h2><label className={button+' cursor-pointer'}>Cargar fotos por modelo<input aria-label="Cargar fotos por modelo" type="file" accept="image/jpeg,image/png,image/webp,image/avif" multiple className="sr-only" disabled={locked} onChange={photos}/></label><button className={button} disabled={locked} onClick={()=>{changeRows([]);setEditing(null);}}>Vaciar borrador</button></div>
          <p className="text-sm text-slate-500">Para varias fotos, nombra cada archivo con el modelo completo: MODELO.jpg. La coincidencia debe ser única. Cargar imágenes no publica el lote.</p>
          <div className="overflow-auto"><table className="w-full text-sm min-w-[880px]"><thead><tr>{['ID','Modelo','Nombre','Precio MXN','Stock','Acciones'].map(t=><th key={t} className="p-2 text-left">{t}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t"><td className="p-2 w-14">{r.id||'Nuevo'}</td>{['model','name','price','stock'].map(k=><td className="p-2" key={k}><input aria-label={`${k} fila ${i+1}`} className={input} disabled={locked} value={r[k]||''} onChange={e=>edit(i,k,e.target.value)}/></td>)}<td className="p-2 whitespace-nowrap"><button className={button} onClick={()=>setEditing(editing===i?null:i)}>Ficha y fuentes</button><button aria-label={`Quitar fila ${i+1}`} className="p-2 text-red-600" disabled={locked} onClick={()=>{changeRows(rows.filter((_,j)=>i!==j));setEditing(null);}}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>
          {editing!==null&&rows[editing]&&<div className="rounded-xl bg-slate-50 p-5 space-y-4"><h3 className="font-bold">Ficha y fuentes · fila {editing+1}</h3>
            <div className="grid gap-4 md:grid-cols-2"><label className="text-sm">Categoría<select className={input} value={rows[editing].category||''} disabled={locked} onChange={e=>edit(editing,'category',e.target.value)}><option value="">Conservar actual</option>{catalog.data?.categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="text-sm">Imagen (URL o ruta de la tienda)<input className={input} value={rows[editing].imageUrl||''} disabled={locked} onChange={e=>edit(editing,'imageUrl',e.target.value)}/></label>
            {['description','sourceUrl','sourceModel','imageSourceUrl','sourceNotes'].map(k=><label key={k} className="text-sm">{{description:'Descripción',sourceUrl:'Página de especificaciones',sourceModel:'Modelo exacto de la fuente',imageSourceUrl:'Página de origen de la foto',sourceNotes:'Notas de verificación'}[k]}<input className={input} value={rows[editing][k]||''} disabled={locked} onChange={e=>edit(editing,k,e.target.value)}/></label>)}</div>
            <div className="flex flex-wrap items-center gap-3"><a className="text-blue-700 text-sm underline" target="_blank" rel="noopener noreferrer" href={'https://www.google.com/search?q='+encodeURIComponent('site:samsung.com/mx "'+(rows[editing].model||'')+'"')}><ExternalLink size={14} className="inline mr-1"/>Buscar modelo exacto en Samsung</a>{rows[editing].sourceUrl?.startsWith('https://')&&<a className="text-blue-700 text-sm underline" target="_blank" rel="noopener noreferrer" href={rows[editing].sourceUrl}>Abrir fuente</a>}
              <label className="text-sm">Verificación humana<select className={input} disabled={locked} value={rows[editing].sourceStatus||'pending'} onChange={e=>edit(editing,'sourceStatus',e.target.value)}><option value="pending">Pendiente de revisar</option><option value="reviewed">Modelo, especificaciones y foto revisados</option></select></label></div>
            <p className="text-xs text-slate-500">Compara el sufijo regional, tamaño y foto del modelo exacto. Una foto de referencia no demuestra el estado ni los accesorios de tu unidad. La búsqueda no marca productos como verificados automáticamente.</p>
            {rows[editing].imageUrl&&<img src={rows[editing].imageUrl} alt={`Vista previa ${rows[editing].model}`} referrerPolicy="no-referrer" className="h-40 max-w-full object-contain bg-white rounded-xl"/>}
          </div>}
          <button className={primary} disabled={locked} onClick={()=>{try{previewMutation.mutate({rows:toApiRows(rows)});}catch(e){toast.error(e.message);}}}>{previewMutation.isPending?'Validando…':'Revisar lote'}</button>
        </section>}
        {preview&&<section className="bg-white rounded-2xl p-5 border border-slate-200 space-y-4" aria-label="Vista previa del lote"><h2 className="text-xl font-bold">3. Confirma los cambios</h2><p>{preview.creates} nuevos · {preview.updates} actualizados · {preview.errors.length} errores</p>{preview.errors.length>0&&<ul role="alert" className="bg-red-50 text-red-800 rounded-xl p-4">{preview.errors.map(e=><li key={e.row}>Fila {e.row}: {e.message}</li>)}</ul>}
          <div className="max-h-96 overflow-auto space-y-3">{preview.plans.map(p=><div className="rounded-xl border p-3 text-sm" key={p.row}><strong>Fila {p.row} · {p.model} · {p.action==='create'?'Crear':'Actualizar'}</strong>{p.changes.map(k=><p key={k} className="break-words text-slate-600"><span className="font-semibold">{k}</span>: {String(p.before?.[k]??'—').slice(0,130)} → {typeof p.data[k]==='object'?JSON.stringify(p.data[k]):String(p.data[k]).slice(0,180)}</p>)}{p.evidence&&<p>Fuentes: {p.evidence.status==='reviewed'?'revisadas por administrador':'pendientes'}</p>}</div>)}</div>
          <p className="text-sm text-slate-500">Se guarda todo el lote o nada. Si cambió el stock u otro dato desde la revisión, tendrás que revisar de nuevo. No se eliminan productos.</p><button className={primary} disabled={locked||!!preview.errors.length} onClick={()=>applyMutation.mutate({rows:toApiRows(rows),token:preview.token,requestId:preview.requestId})}><CheckCircle2 size={17} className="inline mr-2"/>{applyMutation.isPending?'Guardando lote…':`Guardar ${preview.plans.length} productos`}</button>
        </section>}
        </>}
      </>}
    </main>
  </div>;
}
