// @ts-nocheck
import { useState } from 'react';
import { Link } from 'react-router';
import { trpc } from '@/providers/trpc';
import { toast } from 'sonner';
const parse=v=>typeof v==='string'?JSON.parse(v):v;
export function ActionForm({title,fields,onSubmit,initial={},submit='Guardar'}) {
 const [values,setValues]=useState(initial),[busy,setBusy]=useState(false);
 return <form className="commerce-card commerce-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await onSubmit(values);toast.success('Operación completada');}catch(e){toast.error(e.message);}finally{setBusy(false);}}}><h3>{title}</h3>{fields.map(f=><label key={f.key}>{f.label}{f.options?<select value={values[f.key]||f.options[0][0]} onChange={e=>setValues({...values,[f.key]:e.target.value})}>{f.options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:f.type==='checkbox'?<input type="checkbox" checked={!!values[f.key]} onChange={e=>setValues({...values,[f.key]:e.target.checked})}/>:f.type==='textarea'?<textarea required={!f.optional} value={values[f.key]||''} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>:<input required={!f.optional} min={f.min} max={f.max} type={f.type||'text'} value={values[f.key]??''} onChange={e=>setValues({...values,[f.key]:f.type==='number'?Number(e.target.value):e.target.value})}/> }</label>)}<button className="commerce-primary" disabled={busy}>{busy?'Procesando…':submit}</button></form>;
}
const field=(key,label,type='text',optional=false)=>({key,label,type,optional});
export default function CommerceOperations(){
 const [tab,setTab]=useState('overview'),[secret,setSecret]=useState(''); const utils=trpc.useUtils();const {data,error}=trpc.commerce.operations.useQuery();const {data:keys=[]}=trpc.passkey.list.useQuery();const {data:monitor}=trpc.commerce.monitor.useQuery();const {data:refunds=[]}=trpc.commerce.refunds.useQuery();
 const inspected=trpc.commerce.inspectedReturn.useMutation();const zone=trpc.commerce.saveZone.useMutation(),benefit=trpc.commerce.saveBenefit.useMutation(),config=trpc.commerce.rewardsConfig.useMutation(),channel=trpc.commerce.createChannel.useMutation(),channelStatus=trpc.commerce.channelStatus.useMutation(),profile=trpc.commerce.saveProfile.useMutation(),refund=trpc.commerce.refund.useMutation(),reconcile=trpc.commerce.refundReconcile.useMutation(),quote=trpc.commerce.quoteClose.useMutation(),caseStatus=trpc.commerce.caseStatus.useMutation(),booking=trpc.commerce.bookingStatus.useMutation(),fulfill=trpc.commerce.fulfillReward.useMutation(),regOptions=trpc.passkey.registerOptions.useMutation(),register=trpc.passkey.register.useMutation(),remove=trpc.passkey.remove.useMutation();
 async function refresh(fn){await fn();await utils.commerce.invalidate();await utils.passkey.invalidate();}
 const tabs=[['overview','Resumen'],['profiles','Unidades'],['delivery','Entregas'],['sales','Ventas'],['support','Posventa'],['rewards','Recompensas'],['security','Seguridad'],['channels','Canales']];
 return <main className="commerce-page"><header className="commerce-header"><div><span className="commerce-eyebrow">SAMSUNG STORE MX · OPERACIONES</span><h1>Control maestro</h1><p>Datos actuales, decisiones claras.</p></div><Link to="/admin">Panel general ↗</Link></header><nav className="commerce-tabs">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} aria-pressed={tab===id}>{label}</button>)}</nav>{error?<p role="alert">{error.message}</p>:!data?<p>Cargando operación…</p>:<>
 {tab==='overview'&&<><section className="commerce-card"><h2>Estado del sitio y respaldos</h2>{monitor?.health?<p>{monitor.health.ok?'Servicios saludables':'Revisión requerida'} · {new Date(monitor.health.at).toLocaleString('es-MX')} · {Object.entries(monitor.health.checks).map(([k,v])=>`${k}: ${v?'OK':'FALLO'}`).join(' · ')}</p>:<p>El monitor aún no registra datos. Ejecuta el instalador de monitoreo en el VPS.</p>}{monitor?.backup&&<p>Restauración verificada: {new Date(monitor.backup.at).toLocaleString('es-MX')} · SHA-256 {monitor.backup.sha256}</p>}</section><div className="commerce-metrics"><article><strong>{data.inventory[0].products}</strong>Modelos</article><article><strong>{data.inventory[0].units}</strong>Unidades</article><article><strong>{data.cases.filter(c=>!['closed','resolved'].includes(c.status)).length}</strong>Casos abiertos (últimos 100)</article></div><section className="commerce-card"><h2>Existencias bajas</h2>{data.lowStock.length?data.lowStock.map(p=><p key={p.id}>{p.model} · {p.name} <b>{p.stock} disponibles</b></p>):<p>No hay modelos con menos de 3 unidades.</p>}</section><section className="commerce-card"><h2>Pedidos por estado</h2>{data.orders.map(r=><p key={r.status}>{r.status}: {r.orders} pedidos · ${Number(r.total).toLocaleString('es-MX')} MXN</p>)}</section></>}
 {tab==='profiles'&&<ActionForm title="Ficha de unidad de exhibición" fields={[field('productId','ID de producto','number'),field('unitCode','Código de unidad'),field('condition','Estado real / detalles estéticos','textarea'),field('gallery','Rutas de fotos cargadas, una por línea','textarea'),field('accessories','Accesorios, uno por línea','textarea'),field('warranty','Garantía aplicable a esta unidad','textarea'),field('widthMm','Ancho sin base (mm)','number',true),field('heightMm','Alto sin base (mm)','number',true),field('depthMm','Profundidad sin base (mm)','number',true),field('source','Fuente HTTPS de medidas', 'url',true)]} onSubmit={v=>refresh(()=>profile.mutateAsync({productId:v.productId,profile:{unitCode:v.unitCode,condition:v.condition,gallery:v.gallery.split('\n').map(s=>s.trim()).filter(Boolean),accessories:v.accessories.split('\n').filter(Boolean),warranty:v.warranty,...(v.widthMm?{dimensions:{widthMm:v.widthMm,heightMm:v.heightMm,depthMm:v.depthMm,source:v.source}}:{})}}))}/>}
 {tab==='delivery'&&<><ActionForm title="Cobertura por código postal" initial={{daysAhead:2,dailyCapacity:5,active:true,deliveryCents:0,installationCents:0}} fields={[field('postalCode','Código postal (5 dígitos)'),field('label','Zona / servicio'),field('deliveryCents','Entrega en centavos MXN','number'),field('installationCents','Instalación en centavos MXN','number'),field('daysAhead','Anticipación mínima (días)','number'),field('dailyCapacity','Cupos por día','number'),field('active','Zona activa','checkbox')]} onSubmit={v=>refresh(()=>zone.mutateAsync(v))}/><section className="commerce-card"><h2>Zonas publicadas</h2>{data.zones.map(z=><p key={z.id}>{z.postalCode} · {z.label} · ${Number(z.deliveryCents)/100} entrega · {z.dailyCapacity} cupos · {z.active?'Activa':'Inactiva'}</p>)}</section><section className="commerce-card"><h2>Agenda</h2>{data.bookings.map(b=><div key={b.id}><p>Pedido #{b.orderId} · {String(b.serviceDate).slice(0,10)} · {b.status}</p><button onClick={()=>refresh(()=>booking.mutateAsync({id:b.id,status:'scheduled'})).catch(e=>toast.error(e.message))}>Programar</button><button onClick={()=>refresh(()=>booking.mutateAsync({id:b.id,status:'completed'})).catch(e=>toast.error(e.message))}>Completar</button></div>)}</section></>}
 {tab==='sales'&&<><ActionForm title="Confirmar recepción e inspección de devolución" fields={[field('orderId','Pedido con reembolso confirmado','number')]} submit="Reintegrar unidad inspeccionada" onSubmit={v=>refresh(()=>inspected.mutateAsync(v))}/><ActionForm title="Reembolso completo de pago confirmado" fields={[field('orderId','Pedido','number'),field('reason','Motivo','textarea')]} submit="Solicitar reembolso" onSubmit={v=>refresh(()=>refund.mutateAsync(v))}/><section className="commerce-card"><h2>Conciliación de reembolsos</h2>{refunds.map(r=><p key={r.id}>#{r.orderId} · ${Number(r.amountCents)/100} · {r.state} <button onClick={()=>refresh(()=>reconcile.mutateAsync({id:r.id})).catch(e=>toast.error(e.message))}>Consultar proveedor</button></p>)}</section><section className="commerce-card"><h2>Cotizaciones</h2>{data.quotes.map(q=><p key={q.id}>{q.id.slice(0,8)} · ${Number(parse(q.snapshot).total).toLocaleString('es-MX')} · {q.status} · vence {new Date(q.expiresAt).toLocaleString('es-MX')} {q.status==='open'&&<button onClick={()=>refresh(()=>quote.mutateAsync({id:q.id})).catch(e=>toast.error(e.message))}>Cerrar seguimiento</button>}</p>)}</section></>}
 {tab==='support'&&<section className="commerce-card"><h2>Casos y evidencia privada</h2>{data.cases.map(c=><div key={c.id}><Link to={`/mi-cuenta?case=${c.id}`}>#{c.id} · {c.subject} · {c.email}</Link><p>Pedido #{c.orderId} · {c.kind} · {c.status}</p><select value={c.status} onChange={e=>refresh(()=>caseStatus.mutateAsync({id:c.id,status:e.target.value})).catch(e=>toast.error(e.message))}>{['open','review','resolved','closed'].map(s=><option key={s}>{s}</option>)}</select></div>)}</section>}
 {tab==='rewards'&&<><ActionForm title="Regla de puntos (pedidos pagados y entregados)" initial={parse(data.settings.find(s=>s.name==='rewards')?.body)||{enabled:false,pointsPer100:1}} fields={[field('enabled','Activar programa','checkbox'),field('pointsPer100','Puntos por cada $100 MXN completos','number')]} onSubmit={v=>refresh(()=>config.mutateAsync(v))}/><ActionForm title="Beneficio canjeable" initial={{active:true}} fields={[field('id','ID para editar (opcional)','number',true),field('name','Nombre'),field('description','Qué incluye','textarea'),field('points','Costo en puntos','number'),field('active','Publicado','checkbox')]} onSubmit={v=>refresh(()=>benefit.mutateAsync({...v,id:v.id||undefined}))}/><section className="commerce-card"><h2>Canjes</h2>{data.redemptions.map(r=><p key={r.id}>{parse(r.snapshot).name} · cuenta #{r.userId} · {r.status} {r.status==='issued'&&<button onClick={()=>refresh(()=>fulfill.mutateAsync({id:r.id})).catch(e=>toast.error(e.message))}>Marcar entregado</button>}</p>)}</section></>}
 {tab==='security'&&<><ActionForm title="Agregar passkey" fields={[field('label','Nombre de dispositivo'),field('password','Contraseña actual','password')]} submit="Registrar llave de acceso" onSubmit={async v=>{const start=await regOptions.mutateAsync({password:v.password});const {startRegistration}=await import('@simplewebauthn/browser');const response=await startRegistration({optionsJSON:start.options});await refresh(()=>register.mutateAsync({id:start.id,response,label:v.label}));}}/><section className="commerce-card"><h2>Llaves de esta cuenta</h2>{keys.map(k=><ActionForm key={k.id} title={k.label} fields={[field('password','Contraseña para revocar','password')]} submit="Revocar llave" onSubmit={v=>refresh(()=>remove.mutateAsync({id:k.id,password:v.password}))}/>)}</section><section className="commerce-card"><h2>Historial administrativo</h2><p>Últimos 100 eventos. La política CSP está en modo de reporte.</p><div className="commerce-table"><table><thead><tr><th>Fecha</th><th>Cuenta</th><th>Acción</th><th>Recurso</th></tr></thead><tbody>{data.audit.map(a=><tr key={a.id}><td>{new Date(a.createdAt).toLocaleString('es-MX')}</td><td>{a.actorId}</td><td>{a.action}</td><td>{a.resourceId}</td></tr>)}</tbody></table></div></section></>}
 {tab==='channels'&&<><ActionForm title="Conectar inventario de otro canal" fields={[field('label','Nombre del canal / punto de venta')]} onSubmit={async v=>{const r=await channel.mutateAsync(v);setSecret(`ID: ${r.id}\nToken: ${r.secret}`);await utils.commerce.invalidate();}}/>{secret&&<section className="commerce-card"><h2>Token mostrado una sola vez</h2><textarea readOnly value={secret}/><button onClick={()=>setSecret('')}>Ocultar</button></section>}<section className="commerce-card"><p>El conector utiliza el inventario central mediante /api/inventory/ID y /api/inventory/ID/sale. Cada venta lleva un eventId único y Authorization: Bearer TOKEN. Configura el adaptador de tu punto de venta o marketplace antes de habilitar ventas externas.</p>{data.channels.map(c=><p key={c.id}>{c.label} · {c.enabled?'Activo':'Desactivado'} <button onClick={()=>refresh(()=>channelStatus.mutateAsync({id:c.id,enabled:!c.enabled})).catch(e=>toast.error(e.message))}>{c.enabled?'Desactivar':'Activar'}</button></p>)}</section></>}
 </>}</main>;
}
