// @ts-nocheck
import { useState } from 'react';
import { Link,useSearchParams } from 'react-router';
import { trpc } from '@/providers/trpc';
import { ActionForm } from './CommerceOperations';
import { toast } from 'sonner';
const parse=v=>typeof v==='string'?JSON.parse(v):v;
export default function CustomerPortal(){
 const [params]=useSearchParams(),[caseId,setCaseId]=useState(Number(params.get('case'))||0),[files,setFiles]=useState([]);const utils=trpc.useUtils();
 const {data,error}=trpc.commerce.portal.useQuery(),{data:orders=[]}=trpc.order.list.useQuery(),{data:messages=[]}=trpc.commerce.messages.useQuery({id:caseId},{enabled:caseId>0});const cancelCheckout=trpc.commerce.cancelCheckout.useMutation();const create=trpc.commerce.caseCreate.useMutation(),reply=trpc.commerce.reply.useMutation(),redeem=trpc.commerce.redeem.useMutation();
 return <main className="commerce-page"><header className="commerce-header"><div><span className="commerce-eyebrow">SAMSUNG STORE MX · TU CUENTA</span><h1>Estamos contigo</h1><p>Pedidos, atención y beneficios en un solo lugar.</p></div><Link to="/">Volver a la tienda ↗</Link></header>{error?<p role="alert">{error.message}</p>:!data?<p>Cargando tu cuenta…</p>:<>
 <section className="commerce-card"><h2>Mis pedidos</h2>{orders.length?orders.map(o=><p key={o.id}><Link to="/mis-pedidos">Pedido #{o.id}</Link> · {o.status} · ${Number(o.total).toLocaleString('es-MX')} MXN {o.status==='pending'&&<button onClick={async()=>{try{await cancelCheckout.mutateAsync({orderId:o.id});await utils.order.invalidate();toast.success('Checkout cancelado');}catch(e){toast.error(e.message)}}}>Cancelar checkout Stripe</button>}</p>):<p>Todavía no tienes pedidos.</p>}{data.bookings.map(b=><p key={b.id}>Entrega #{b.orderId} · {String(b.serviceDate).slice(0,10)} · {b.status}</p>)}</section>
 {!!orders.length&&<ActionForm title="Solicitar atención" initial={{orderId:orders[0].id,kind:'support'}} fields={[{key:'orderId',label:'Pedido',options:orders.map(o=>[String(o.id),`Pedido #${o.id}`])},{key:'kind',label:'Tipo',options:[['support','Soporte'],['warranty','Garantía'],['return','Devolución']]},{key:'subject',label:'Asunto'},{key:'message',label:'Describe tu solicitud',type:'textarea'}]} submit="Crear caso" onSubmit={async v=>{const r=await create.mutateAsync({...v,orderId:Number(v.orderId)});setCaseId(r.id);await utils.commerce.portal.invalidate();}}/>}
 <section className="commerce-card"><h2>Seguimiento de casos</h2>{data.cases.map(c=><button key={c.id} onClick={()=>setCaseId(c.id)}>#{c.id} · {c.subject} · {c.status}</button>)}{!data.cases.length&&<p>No tienes solicitudes abiertas.</p>}</section>
 {caseId>0&&<section className="commerce-card"><h2>Conversación #{caseId}</h2><div className="commerce-messages">{messages.map(m=><div key={m.id} className="commerce-message"><small>{new Date(m.createdAt).toLocaleString('es-MX')}</small><p>{m.message}</p>{m.attachments.map(id=><a key={id} href={`/api/support/file/${id}`} target="_blank" rel="noreferrer"><img src={`/api/support/file/${id}`} alt="Evidencia del caso"/></a>)}</div>)}</div><label>Evidencia privada (JPG, PNG o WebP, hasta 5 MB)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files[0];if(!file)return;try{if(files.length>=5)throw new Error('Máximo 5 imágenes');const form=new FormData();form.set('file',file);const res=await fetch('/api/support/file',{method:'POST',body:form,credentials:'include'});const body=await res.json();if(!res.ok)throw new Error(body.error);setFiles(prev=>[...prev,body.id]);toast.success('Evidencia cargada');}catch(e){toast.error(e.message);}finally{e.target.value='';}}}/></label><p>{files.length} imágenes listas para adjuntar.</p><ActionForm title="Enviar respuesta" fields={[{key:'message',label:'Mensaje',type:'textarea'}]} submit="Enviar al caso" onSubmit={async v=>{await reply.mutateAsync({id:caseId,message:v.message,attachments:files});setFiles([]);await utils.commerce.messages.invalidate({id:caseId});}}/></section>}
 <section className="commerce-card"><h2>Tu balance: {data.points} puntos</h2><p>Los puntos se acreditan después del pago y la entrega, según la regla vigente.</p>{data.benefits.map(b=><div key={b.id}><h3>{b.name}</h3><p>{b.description} · {b.points} puntos</p><button disabled={data.points<b.points||redeem.isPending} onClick={async()=>{try{await redeem.mutateAsync({benefitId:b.id});await utils.commerce.portal.invalidate();toast.success('Canje registrado');}catch(e){toast.error(e.message);}}}>Canjear</button></div>)}{data.vouchers.map(v=><p key={v.id}>{parse(v.snapshot).name} · {v.status} · folio {v.id}</p>)}{data.ledger.map((l,i)=><p key={i}>{l.reason}: {l.points>0?'+':''}{l.points}</p>)}</section>
 </>}</main>;
}
