// @ts-nocheck
import { useState } from 'react';
import { Link,useParams } from 'react-router';
import { trpc } from '@/providers/trpc';
import { ActionForm } from './CommerceOperations';
import { useAuth } from '@/hooks/useAuth';
export default function SharedQuote(){
 const {token}=useParams();const {user}=useAuth();const {data:q,error}=trpc.commerce.quote.useQuery({token}),{data:providers=[]}=trpc.order.paymentProviders.useQuery();const utils=trpc.useUtils();const [delivery,setDelivery]=useState(null),[draft,setDraft]=useState(null);const checkout=trpc.order.checkout.useMutation();const [key]=useState(()=>{const name=`quote-request-${token}`;let v=sessionStorage.getItem(name);if(!v){v=crypto.randomUUID();sessionStorage.setItem(name,v);}return v;});
 return <main className="commerce-page"><header className="commerce-header"><div><span className="commerce-eyebrow">SAMSUNG STORE MX</span><h1>Tu selección, por escrito</h1></div><Link to="/">Tienda ↗</Link></header>{error?<p role="alert">{error.message}</p>:!q?<p>Cargando cotización…</p>:<><section className="commerce-card"><h2>Cotización {q.id.slice(0,8)}</h2><p>Vence {new Date(q.expiresAt).toLocaleString('es-MX')}. Precio fijo hasta el vencimiento; disponibilidad sujeta a existencias al pagar.</p><div className="commerce-product-grid">{q.snapshot.items.map(p=><article key={p.productId}><img src={p.image} alt={p.name}/><h3>{p.name}</h3><p>{p.quantity} × ${Number(p.price).toLocaleString('es-MX')} MXN</p></article>)}</div><h2>Total de productos: ${Number(q.snapshot.total).toLocaleString('es-MX')} MXN</h2>{(q.expired||q.status!=='open')&&<p>Esta cotización está {q.expired?'vencida':q.status}.</p>}</section>{!q.expired&&q.status==='open'&&(user?providers.length?<ActionForm title="Finalizar cotización" initial={{provider:providers[0]}} fields={[{key:'name',label:'Nombre completo'},{key:'email',label:'Correo',type:'email'},{key:'phone',label:'Teléfono'},{key:'address',label:'Dirección'},{key:'city',label:'Ciudad'},{key:'postalCode',label:'Código postal'},{key:'provider',label:'Pago',options:providers.map(p=>[p,p==='stripe'?'Stripe':'Mercado Pago'])}]} submit="Consultar entrega" onSubmit={async v=>{const {provider,...shippingAddress}=v;const zone=await utils.commerce.service.fetch({postalCode:shippingAddress.postalCode});if(!zone)throw new Error('Sin cobertura publicada. Solicita atención comercial.');setDraft({provider,shippingAddress});setDelivery(zone);}}/>:<p>Pago en línea pendiente de habilitación. Conserva el enlace para atención comercial.</p>:<Link to="/login">Inicia sesión con la cuenta que creó la cotización para finalizar.</Link>)}{delivery&&draft&&<ActionForm title={`Entrega · ${delivery.label} · $${Number(delivery.deliveryCents)/100} MXN`} initial={{date:'',installation:false}} fields={[{key:'date',label:'Fecha',options:[['','Selecciona fecha'],...delivery.dates.filter(d=>d.available>0).map(d=>[d.date,`${d.date} · ${d.available} cupos`])]},{key:'installation',label:`Instalación +$${Number(delivery.installationCents)/100} MXN`,type:'checkbox'}]} submit="Ir al pago seguro" onSubmit={async v=>{if(!v.date)throw new Error('Selecciona fecha');const result=await checkout.mutateAsync({...draft,requestKey:key,quoteToken:token,service:{zoneId:delivery.id,date:v.date,installation:!!v.installation},items:q.snapshot.items.map(p=>({productId:p.productId,quantity:p.quantity}))});if(result.url)window.location.assign(result.url);}}/>}</>}</main>;
}
