name: Auto Deploy VPS

on:
  push:
    branches:
      - samsung-store-mx

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 69.6.207.180
          username: root
          port: 22022
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/app
            git pull origin samsung-store-mx
            npm install
            npm run build
            pm2 restart api
            systemctl reload nginx
            echo "✅ AUTO DEPLOY OK"
